# Generated by Django 3.2.7 on 2021-10-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='race',
        ),
    ]
