# Generated by Django 3.2.7 on 2021-10-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0003_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='id1',
        ),
    ]
