# Generated by Django 3.2.7 on 2021-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0004_remove_race_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='rt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
