# Generated by Django 3.2.7 on 2021-10-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0006_remove_race_rt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='race',
        ),
    ]
