# Generated by Django 3.2.7 on 2021-10-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0012_race_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('id_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_mascotas.race')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_mascotas.type')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_mascotas.user')),
            ],
        ),
    ]
