# Generated by Django 3.2.7 on 2021-10-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20210928_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='tipo',
            new_name='tipo_marca',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
